export const practiceQuestions = [
  { dayId: 1, prompt: "اكتب الأمر الذي يعرض نوع الـ Shell الحالي.", answers: ["echo $SHELL", 'echo "$SHELL"'], hint: "استخدم echo مع المتغير $SHELL", explanation: "echo $SHELL يطبع قيمة متغير البيئة SHELL." },
  { dayId: 1, prompt: "اكتب الأمر الذي يعرض اسم نظام التشغيل الأساسي.", answers: ["uname -s"], hint: "الأمر uname مع الخيار -s", explanation: "uname -s يطبع Darwin أو Linux." },
  { dayId: 1, prompt: "اكتب الأمر الذي يعرض المسار الحالي الكامل.", answers: ["pwd"], hint: "Print Working Directory", explanation: "pwd يعرض مكانك الحالي." },
  { dayId: 1, prompt: "اكتب الأمر للرجوع للمجلد الأب خطوة واحدة.", answers: ["cd .."], hint: "cd ومعها نقطتين", explanation: "cd .. ينقلك إلى Parent Directory." },
  { dayId: 1, prompt: "اكتب الأمر للانتقال إلى Home Directory.", answers: ["cd ~", "cd"], hint: "cd ومعها علامة ~", explanation: "cd ~ ينقلك إلى مجلد البيت." },
  { dayId: 1, prompt: "اكتب الأمر لعرض كل الملفات بالتفاصيل وبالأحجام المقروءة.", answers: ["ls -lah", "ls -la -h", "ls -alh", "ls -lha"], hint: "ls مع l و a و h", explanation: "ls -lah يعرض الملفات المخفية والتفاصيل." },
  { dayId: 1, prompt: "اكتب الأمر للرجوع إلى المجلد السابق قبل آخر cd.", answers: ["cd -"], hint: "cd مع شرطة", explanation: "cd - يعيدك للمكان الذي كنت فيه." },
  { dayId: 1, prompt: "اكتب الأمر لإنشاء مجلد تدريب terminal-practice والدخول إليه (سطرين أو سطر واحد).", answers: ["mkdir terminal-practice && cd terminal-practice", "mkdir terminal-practice; cd terminal-practice"], hint: "mkdir ثم cd", explanation: "من تمرين اليوم 1 في الكتيب." },
  { dayId: 1, prompt: "اكتب الأمر لفتح دليل المساعدة لأمر ls.", answers: ["man ls"], hint: "man + اسم الأمر", explanation: "man ls يفتح صفحة المساعدة." },
  { dayId: 1, prompt: "اكتب الأمر لمعرفة نوع أمر cd (builtin أم ملف).", answers: ["type cd"], hint: "type + الأمر", explanation: "type يوضح إن كان الأمر builtin أو مسارًا." },
  { dayId: 1, prompt: "اكتب الأمر لعرض مساعدة الأمر الداخلي cd.", answers: ["help cd"], hint: "help + الأمر", explanation: "help للأوامر builtin في الـ shell." },
  { dayId: 1, prompt: "اكتب الأمر لمعرفة مسار تنفيذ git على النظام.", answers: ["which git"], hint: "which + الأمر", explanation: "which يعرض مسار البرنامج." },
  { dayId: 1, prompt: "اكتب الأمر لعرض إصدار Homebrew.", answers: ["brew --version"], hint: "brew --version", explanation: "للتحقق من تثبيت brew على macOS." },
  { dayId: 2, prompt: "اكتب الأمر لإنشاء مجلد جديد باسم study.", answers: ["mkdir study"], hint: "mkdir + اسم المجلد", explanation: "mkdir study ينشئ مجلدًا جديدًا." },
  { dayId: 2, prompt: "اكتب الأمر لإنشاء مسار project/src/components دفعة واحدة.", answers: ["mkdir -p project/src/components"], hint: "mkdir -p", explanation: "mkdir -p ينشئ المجلدات الناقصة." },
  { dayId: 2, prompt: "اكتب الأمر لإنشاء ملف فارغ باسم Lesson1.txt.", answers: ["touch Lesson1.txt"], hint: "touch + اسم الملف", explanation: "touch ينشئ ملفًا فارغًا." },
  { dayId: 2, prompt: "اكتب الأمر لإعادة تسمية photo.png إلى avatar.png.", answers: ["mv photo.png avatar.png"], hint: "mv القديم الجديد", explanation: "mv للنقل أو إعادة التسمية." },
  { dayId: 2, prompt: "اكتب الأمر لنسخ file.txt إلى backup.txt.", answers: ["cp file.txt backup.txt"], hint: "cp المصدر الوجهة", explanation: "cp ينسخ الملف." },
  { dayId: 2, prompt: "اكتب الأمر لنسخ notes.txt إلى مجلد backup/.", answers: ["cp notes.txt backup/"], hint: "cp إلى مجلد", explanation: "من تمرين اليوم 2 في الكتيب." },
  { dayId: 2, prompt: "اكتب الأمر لحذف مجلد backup ومحتوياته.", answers: ["rm -r backup", "rm -rf backup"], hint: "rm -r", explanation: "rm -r يحذف المجلد متكررًا." },
  { dayId: 2, prompt: "اكتب الأمر لمعرفة نوع ملف script.sh.", answers: ["file script.sh"], hint: "file + اسم الملف", explanation: "file يحدد نوع الملف." },
  { dayId: 2, prompt: "اكتب الأمر لعرض معلومات تفصيلية عن file.txt.", answers: ["stat file.txt"], hint: "stat + الملف", explanation: "stat يعرض بيانات الملف التفصيلية." },
  { dayId: 2, prompt: "اكتب الأمر لنسخ مجلد project بالكامل إلى project-backup.", answers: ["cp -r project project-backup"], hint: "cp -r", explanation: "cp -r ينسخ المجلد متكررًا." },
  { dayId: 2, prompt: "اكتب الأمر لحذف مجلد folder ومحتواه بالقوة (بحذر).", answers: ["rm -rf folder"], hint: "rm -rf", explanation: "حذف نهائي — تأكد من المسار." },
  { dayId: 3, prompt: "اكتب الأمر لعرض محتوى ملف app.log بالكامل.", answers: ["cat app.log"], hint: "cat + الملف", explanation: "cat للملفات الصغيرة." },
  { dayId: 3, prompt: "اكتب الأمر لفتح app.log للتصفح التفاعلي.", answers: ["less app.log"], hint: "less + الملف", explanation: "less للملفات الكبيرة." },
  { dayId: 3, prompt: "اكتب الأمر لعرض أول 10 أسطر من app.log.", answers: ["head -n 10 app.log", "head app.log"], hint: "head -n 10", explanation: "head يعرض أول الأسطر." },
  { dayId: 3, prompt: "اكتب الأمر لعرض آخر سطرين من app.log.", answers: ["tail -n 2 app.log"], hint: "tail -n 2", explanation: "من تمرين اليوم 3 في الكتيب." },
  { dayId: 3, prompt: "اكتب الأمر للبحث عن ERROR داخل app.log.", answers: ['grep "ERROR" app.log', "grep ERROR app.log"], hint: "grep + النص", explanation: "grep يبحث داخل الملف." },
  { dayId: 3, prompt: "اكتب الأمر للبحث عن ERROR مع عرض أرقام الأسطر.", answers: ['grep -n "ERROR" app.log'], hint: "grep -n", explanation: "grep -n يضيف أرقام الأسطر." },
  { dayId: 3, prompt: "اكتب الأمر لعدّ أسطر ملف app.log.", answers: ["wc -l app.log"], hint: "wc -l", explanation: "wc -l يعدّ الأسطر." },
  { dayId: 4, prompt: "اكتب الأمر لعدّ عدد أسطر ERROR في app.log باستخدام pipe.", answers: ['grep "ERROR" app.log | wc -l', 'grep ERROR app.log | wc -l'], hint: "grep ثم | wc -l", explanation: "pipe يربط grep مع wc -l." },
  { dayId: 4, prompt: "اكتب الأمر لترتيب أسطر names.txt ثم حذف التكرار مع عدّ التكرارات.", answers: ["sort names.txt | uniq -c"], hint: "sort | uniq -c", explanation: "uniq يعمل على أسطر متجاورة بعد sort." },
  { dayId: 4, prompt: "اكتب الأمر لتحويل hello إلى أحرف كبيرة باستخدام tr.", answers: ["echo hello | tr 'a-z' 'A-Z'", 'echo "hello" | tr a-z A-Z'], hint: "tr مع pipe", explanation: "tr يحوّل الأحرف." },
  { dayId: 3, prompt: "اكتب الأمر للتحقق بصمت إن كان ERROR موجودًا في app.log (بدون طباعة ناتج).", answers: ['grep -q "ERROR" app.log', "grep -q ERROR app.log", "grep -q 'ERROR' app.log"], hint: "grep -q", explanation: "grep -q يعتمد على exit code فقط." },
  { dayId: 4, prompt: "اكتب أمرًا يقرأ file.txt ثم يبحث عن hello باستخدام Pipe.", answers: ["cat file.txt | grep hello", "cat file.txt|grep hello"], hint: "cat | grep", explanation: "| يمرر الناتج." },
  { dayId: 4, prompt: "اكتب أمرًا يحفظ ناتج ls داخل tolal_fals.txt مع مسح القديم.", answers: ["ls > tolal_fals.txt"], hint: ">", explanation: "> يكتب ويمسح القديم." },
  { dayId: 4, prompt: "اكتب أمرًا يضيف hello في نهاية filename.txt.", answers: ["echo hello >> filename.txt", 'echo "hello" >> filename.txt'], hint: ">>", explanation: ">> للإضافة." },
  { dayId: 4, prompt: "اكتب أمرًا يحفظ أخطاء أمر ls لملف غير موجود في errors.txt.", answers: ["ls not-found 2> errors.txt"], hint: "2>", explanation: "2> يوجّه stderr." },
  { dayId: 4, prompt: "اكتب أمرًا يجمع stdout وstderr في all.txt (مثال: ls .).", answers: ["ls . > all.txt 2>&1", "ls > all.txt 2>&1"], hint: "> ملف 2>&1", explanation: "2>&1 يدمج التدفقات." },
  { dayId: 4, prompt: "اكتب أمرًا يعدّ أسطر ERROR في app.log.", answers: ['grep "ERROR" app.log | wc -l'], hint: "grep | wc -l", explanation: "من تمرين اليوم 4 في الكتيب." },
  { dayId: 4, prompt: "اكتب أمرًا يعرض أول 10 أسطر ثم يعدّها.", answers: ["head -n 10 questions-source.txt | wc -l", "head questions-source.txt | wc -l"], hint: "head | wc -l", explanation: "pipeline بسيط." },
  { dayId: 4, prompt: "اكتب أمرًا يبحث عن (صح) ويضيف النتيجة لـ filename.txt.", answers: ['grep -i "(صح)" questions-source.txt >> filename.txt', "grep -i '(صح)' questions-source.txt >> filename.txt"], hint: "grep >>", explanation: "جمع بحث وإضافة." },
  { dayId: 4, prompt: "اكتب أمرًا يعرض الملفات المخفية ويحفظ الناتج في tolal_fals.txt.", answers: ["ls -la > tolal_fals.txt", "ls -lah > tolal_fals.txt"], hint: "ls -la >", explanation: "redirect بعد ls." },
  { dayId: 5, prompt: "اكتب الأمر للبحث عن كل ملفات .txt في المجلد الحالي.", answers: ['find . -type f -name "*.txt"', "find . -type f -name '*.txt'"], hint: "find . -type f", explanation: "find للبحث عن ملفات." },
  { dayId: 5, prompt: "اكتب الأمر للبحث عن مجلدات باسم node_modules.", answers: ['find . -type d -name "node_modules"', "find . -type d -name node_modules"], hint: "find -type d", explanation: "type d للمجلدات." },
  { dayId: 5, prompt: "اكتب الأمر لعرض مسارات ملفات .log قبل حذفها.", answers: ['find . -name "*.log" -print', 'find . -type f -name "*.log" -print'], hint: "find -print", explanation: "معاينة قبل الحذف." },
  { dayId: 5, prompt: "اكتب الأمر لحذف كل ملفات .log في المجلد الحالي.", answers: ['find . -type f -name "*.log" -delete', 'find . -name "*.log" -delete'], hint: "find -delete", explanation: "بعد التأكد بـ -print." },
  { dayId: 5, prompt: "اكتب أمرًا يعدّ ملفات txt باستخدام find و pipe.", answers: ['find . -type f -name "*.txt" | wc -l'], hint: "find | wc -l", explanation: "عدّ النتائج." },
  { dayId: 5, prompt: "اكتب أمرًا يطبّق wc -l على كل ملف txt بـ xargs الآمن.", answers: ['find . -name "*.txt" -print0 | xargs -0 wc -l', 'find . -type f -name "*.txt" -print0 | xargs -0 wc -l'], hint: "-print0 | xargs -0", explanation: "آمن مع المسافات." },
  { dayId: 5, prompt: "اكتب أمرًا يحذف ملفات .log باستخدام find و xargs (الشكل البسيط).", answers: ['find . -name "*.log" | xargs rm'], hint: "find | xargs rm", explanation: "احذر من المسافات في الأسماء." },
  { dayId: 6, prompt: "اكتب الأمر لعرض الملفات مع صلاحيات rwx.", answers: ["ls -l", "ls -la", "ls -lah"], hint: "ls -l", explanation: "ls -l يعرض الصلاحيات." },
  { dayId: 6, prompt: "اكتب الأمر لمعرفة المستخدم الحالي.", answers: ["whoami"], hint: "whoami", explanation: "whoami يطبع اسم المستخدم." },
  { dayId: 6, prompt: "اكتب الأمر لعرض uid والمجموعات للمستخدم الحالي.", answers: ["id"], hint: "id", explanation: "id يعرض تفاصيل الهوية." },
  { dayId: 6, prompt: "اكتب الأمر لجعل build_practice.py قابلًا للتنفيذ.", answers: ["chmod +x build_practice.py"], hint: "chmod +x", explanation: "chmod +x يضيف x." },
  { dayId: 6, prompt: "اكتب الأمر لضبط صلاحيات script.sh إلى 755.", answers: ["chmod 755 script.sh"], hint: "chmod 755", explanation: "755 شائع للسكربتات." },
  { dayId: 6, prompt: "اكتب صيغة تشغيل apt update بصلاحيات المدير.", answers: ["sudo apt update"], hint: "sudo", explanation: "sudo للأوامر الإدارية." },
  { dayId: 6, prompt: "اكتب الأمر لتغيير مالك file.txt إلى ahmed والمجموعة staff.", answers: ["sudo chown ahmed:staff file.txt", "chown ahmed:staff file.txt"], hint: "chown user:group", explanation: "غالبًا يحتاج sudo." },
  { dayId: 7, prompt: "اكتب أمرًا ينشئ study وينتقل إليه في سطر واحد.", answers: ["mkdir study && cd study"], hint: "&&", explanation: "&& يربط أمرين." },
  { dayId: 7, prompt: "اكتب سطر Shebang المحمول لسكربت bash.", answers: ["#!/usr/bin/env bash"], hint: "#!/usr/bin/env", explanation: "أفضل من #!/bin/bash للتنقل بين الأنظمة." },
  { dayId: 7, prompt: "اكتب سطر وضع الأمان في بداية سكربت bash.", answers: ["set -euo pipefail"], hint: "set -euo", explanation: "يوقف عند الخطأ ويحمي المتغيرات." },
  { dayId: 7, prompt: "اكتب الأمر لتشغيل script.sh باستخدام bash.", answers: ["bash script.sh"], hint: "bash script.sh", explanation: "لا يحتاج chmod +x." },
  { dayId: 7, prompt: "اكتب الأمر لعرض مسار البيت من متغير البيئة.", answers: ["echo $HOME", 'echo "$HOME"'], hint: "echo $HOME", explanation: "HOME متغير بيئة." },
  { dayId: 7, prompt: "اكتب الأمر لعرض كود خروج آخر أمر.", answers: ["echo $?"], hint: "echo $?", explanation: "0 نجاح، غيره فشل." },
  { dayId: 7, prompt: "اكتب الأمر لجعل script.sh قابلًا للتشغيل بـ ./script.sh.", answers: ["chmod +x script.sh"], hint: "chmod +x", explanation: "صلاحية تنفيذ." },
  { dayId: 7, prompt: "اكتب الأمر لتشغيل script.sh من المجلد الحالي.", answers: ["./script.sh"], hint: "./", explanation: "يتطلب chmod +x." },
  { dayId: 7, prompt: "اكتب أمرًا يعرض تاريخ الغد على Linux (GNU date).", answers: ['date -d "tomorrow" "+%Y-%m-%d"', 'date -d tomorrow +%Y-%m-%d'], hint: "date -d tomorrow", explanation: "من سكربت portable في الكتيب — Linux." },
  { dayId: 7, prompt: "اكتب أمرًا يعرض تاريخ الغد على macOS (BSD date).", answers: ['date -v+1d "+%Y-%m-%d"'], hint: "date -v+1d", explanation: "من سكربت portable في الكتيب — macOS." },
  { dayId: 7, prompt: "اكتب أمرًا لإنشاء ملف مؤقت وحفظ مساره في متغير tmpfile.", answers: ['tmpfile="$(mktemp)"', "tmpfile=$(mktemp)"], hint: "mktemp", explanation: "mktemp لملف مؤقت آمن." },
  { dayId: 7, prompt: "اكتب الأمر لعرض التاريخ والوقت بصيغة YYYY-MM-DD HH:MM:SS.", answers: ['date "+%Y-%m-%d %H:%M:%S"', 'date +"%Y-%m-%d %H:%M:%S"'], hint: 'date "+%Y-%m-%d"', explanation: "تنسيق date بصيغة strftime." },
  { dayId: 7, prompt: "اكتب بداية شرط if للتحقق من وجود ملف config.txt.", answers: ['if [ -f "config.txt" ]; then', "if [ -f config.txt ]; then", 'if [ -f "config.txt" ]'], hint: "if [ -f", explanation: "-f يتحقق من وجود ملف." },
  { dayId: 7, prompt: "اكتب بداية حلقة for على كل ملفات txt في المجلد.", answers: ["for file in *.txt; do", "for file in *.txt;do"], hint: "for file in *.txt", explanation: "حلقة for على glob." },
  { dayId: 7, prompt: "اكتب بداية حلقة while لقراءة file.txt سطرًا بسطر.", answers: ["while read -r line; do", "while read -r line;do"], hint: "while read -r", explanation: "read -r مع while شائع في السكربتات." },
  { dayId: 7, prompt: "اكتب تعريف دالة log تطبع رسالة ببادئة INFO.", answers: ['log() { echo "[INFO] $*"; }', 'log() { echo "[INFO] $*";}'], hint: "log() { echo", explanation: "دالة bash بسيطة." },
];
